server:
  port: 8080

# Personal Azure Active Directory Service
azure-fdl-tenant-id: a805eb36-3833-4902-88c2-5cb74b2cbcbf

azure-fdl-ui-login-client-id: b19a6e57-ea73-49f9-9a00-37a76b8781ef
azure-fdl-ui-login-client-secret: ODnRXZYNEevlu?Ae5eRqw.M0Vvis]9?7

azure-fdl-ms-graph-api-client-id: 3374cf56-2250-4efd-ad82-97deb40e80c4
azure-fdl-ms-graph-api-client-secret: /pmlOF=?]6WBK9I2Riez0Y@.U8LL[:B=

logging:
  level:
    root: DEBUG
    io.fdlessard.codebites.msgraph.user: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          ui-login:
            client-name: UI Login
            provider: azure
            client-id: ${azure-fdl-ui-login-client-id}
            client-secret: ${azure-fdl-ui-login-client-secret}
            scope: openid,profile,email
          ms-graph-api:
            client-name: Ms Graph Api
            provider: azure
            authorization-grant-type: client_credentials
            client-id: ${azure-fdl-ms-graph-api-client-id}
            client-secret: ${azure-fdl-ms-graph-api-client-secret}
            redirect-uri: "{baseUrl}/ms-graph-api"
####            client-authentication-method: none
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: User.Read
#            scope: openid,profile,email,api://b19a6e57-ea73-49f9-9a00-37a76b8781ef/fdlessard.Read
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${azure-fdl-tenant-id}/v2.0
          azure-nbc:
            issuer-uri: https://login.microsoftonline.com/${azure-nbc-tenant-id}/v2.0
## The following are not needed if you provide issuer-uri
#            authorization-uri: https://login.microsoftonline.com/${azure-tenant-id}/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/${azure-tenant-id}/oauth2/v2.0/token
#            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            user-name-attribute: sub
#            jwk-set-uri: https://login.microsoftonline.com/${azure-tenant-id}/discovery/v2.0/keys